# playbook for debian
---
- hosts: all
  vars_files:
    - vars.yml
  become: yes
  tasks:
    - name: Install packages
      apt: name={{ packages }} state=present update_cache=yes
    
    - name: Install kernel packages
      shell: apt install -y linux-headers-$(uname -r)

    - name: Create user
      user:
        name: "{{ user }}"
        createhome: yes
        password: $1HmkCoVP.ezo
        shell: /usr/bin/fish
        state: present

    - name: Setup authorized keys
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"

    - name: Attach sudo authority
      lineinfile:
        dest: /etc/sudoers
        backup: yes
        line: '"{{ user }}" ALL=(ALL) NOPASSWD: ALL'